#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

<<<<<<< HEAD
#define PROJECT_SOURCE_DIR "C:/Users/justi/Documents/GitHub/team3-BaristaBeatBattle/template/"
=======
#define PROJECT_SOURCE_DIR "C:/Users/Ameya/Desktop/UBC/CPSC 427/team3-BaristaBeatBattle/template/"
>>>>>>> f8181da308fb74bf6991595673aaa2726206846f
