#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "C:/Users/Aticcus/OneDrive/Documents/GitHub/team3-BaristaBeatBattle/template/"
