#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "C:/Users/Ameya/Desktop/UBC/CPSC 427/team3-BaristaBeatBattle/template/"
